version: '3.9'

services:
  mysql-db:
    image: mysql
    container_name: my-ecommerce-db
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_USER=${DATABASE_USERNAME}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    volumes:
      - my-ecommerce-db:/var/lib/mysql

volumes:
  my-ecommerce-db: